### ISSUE TITLE
Heal me!

### ISSUE THREAD

**Issue by Tristan-H11** [Tristan-H11/Minecraft-Plugin#5]
Implementation eines Heal-Befehls: `/heal`

Heilt den Benutzer auf volle Leben.

Optional: 
- Differenzierung zwischen Hunger und Leben durch Parameter
- Differenzierung zwischen Spielern durch Parameter

**Comment by Felefix201** [comment]
jaja mama ...😂

Tristan ***@***.***> schrieb am Do., 6. Jan. 2022, 20:12:

**Comment by Tristan-H11** [comment]
@Felefix201 Du möchtest dann im Branch "Lucas" arbeiten. Du kannst einfach in Intellij unten rechts statt "main" "Lucas" auswählen und dann ganz normal mit committen und oben rechts den Pfeil drücken.
